### ISSUE TITLE
docker启动后登录报错

### ISSUE THREAD

**Issue by YYYet** [danni-cool/docker-wechatbot-webhook#5]
2023-09-28 13:54:28 Scan QR Code to login: 3
2023-09-28 13:54:28 https://wechaty.js.org/qrcode/xxxxxxxxxxxxxxxxx
2023-09-28 13:54:37 uncaughtException AssertionError [ERR_ASSERTION]: 1 == 0
2023-09-28 13:54:37     at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)
2023-09-28 13:54:37     at /app/node_modules/wechat4u/lib/core.js:227:24
2023-09-28 13:54:37     at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
2023-09-28 13:54:37   code: 2,
2023-09-28 13:54:37   details: 'AssertionError [ERR_ASSERTION]: 1 == 0\n' +
2023-09-28 13:54:37     '    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
2023-09-28 13:54:37     '    at /app/node_modules/wechat4u/lib/core.js:227:24\n' +
2023-09-28 13:54:37     '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
2023-09-28 13:54:37 }

**Comment by danni-cool** [comment]
目测是你太久未登录，二维码失效了

**Comment by YYYet** [comment]
使用wechaty-chatgpt的项目可以登录

**Comment by YYYet** [comment]
> 目测是你太久未登录，二维码失效了

可能是需要开通微信支付 晚点我试一下 感谢
