### ISSUE TITLE
带emoji的群名无法发送消息

### ISSUE THREAD

**Issue by samz2z** [danni-cool/docker-wechatbot-webhook#58]
09:06:53 WARN Room find() got more than one(2) result
Error handling POST request: AssertionError [ERR_ASSERTION]: -1 == 0
    at Object.equal (/app/node_modules/.pnpm/wechat4u@0.7.12/node_modules/wechat4u/lib/util/global.js:69:24)
    at /app/node_modules/.pnpm/wechat4u@0.7.12/node_modules/wechat4u/lib/core.js:535:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PuppetWechat4u.messageSendText (/app/node_modules/.pnpm/wechaty-puppet-wechat4u@1.14.6_@swc+core@1.3.78_wechaty-puppet@1.20.2/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:640:9)
    at async WechatifiedUserClass.say (/app/node_modules/.pnpm/wechaty@1.20.2_@swc+core@1.3.78_brolog@1.14.2_redux@4.2.1_rxjs@7.8.1/node_modules/wechaty/dist/cjs/src/user-modules/room.js:371:21)
    at async Object.formatAndSendMsg (/app/src/service/msg.js:8:7)
    at async /app/src/route/msg.js:119:30 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: -1,
  expected: 0,
  operator: '==',
  response: [Object],
  tips: '发送文本信息失败'
}

**Comment by danni-cool** [comment]
emoji群名测试过了，没问题，重启下服务就好了，这个是wechaty历史数据问题。

**Comment by samz2z** [comment]
重启试试可以了
