### ISSUE TITLE
推送文件url 失败

### ISSUE THREAD

**Issue by XHHzZz** [danni-cool/docker-wechatbot-webhook#61]
Error handling POST request: AssertionError [ERR_ASSERTION]: -1 == 0
    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)
    at /app/node_modules/wechat4u/lib/core.js:850:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PuppetWechat4u.messageSendFile (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:660:9)
    at async /app/node_modules/wechaty/dist/cjs/src/sayable/deliver-sayable.js:25:17
    at async WechatifiedUserClass.say (/app/node_modules/wechaty/dist/cjs/src/user-modules/contact.js:300:23)
    at async Object.formatAndSendMsg (/app/src/service/msg.js:17:9)
    at async /app/src/route/msg.js:55:28 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: -1,
  expected: 0,
  operator: '==',
  response: [Object],
  tips: '发送文件失败'
}

大佬帮忙看看为啥子推送文件url失败呢？

**Comment by danni-cool** [comment]
登陆掉了，重新登陆下，web协议出来背锅

**Comment by XHHzZz** [comment]
这个消息发送如果是歌曲类的，微信可以自动识别嘛？还是说就是文件呢？

**Comment by danni-cool** [comment]
> 这个消息发送如果是歌曲类的，微信可以自动识别嘛？还是说就是文件呢？

纯文件，暂不支持歌曲

**Comment by XHHzZz** [comment]
后期会支持　其他类型的消息推送嘛？

**Comment by danni-cool** [comment]
目前web协议不支持这种花里胡哨的
