### ISSUE TITLE
登录状态添加好友，获取不到好友信息

### ISSUE THREAD

**Issue by XHHzZz** [danni-cool/docker-wechatbot-webhook#64]
source 参数值 

{
    "room": "",
    "to": {
        "_events": {},
        "_eventsCount": 0,
        "id": "@acc5cad76fa9ad91f19a7935d49c55560a08ffcd6cae2912a9f1e6ade6416079",
        "payload": {
            "alias": "",
            "avatar": "/cgi-bin/mmwebwx-bin/webwxgeticon?seq=1807265423&username=@acc5cad76fa9ad91f19a7935d49c55560a08ffcd6cae2912a9f1e6ade6416079&skey=@crypt_5f142b66_cf2b90c170d79652d4792207facb2905",
            "friend": False,
            "id": "@acc5cad76fa9ad91f19a7935d49c55560a08ffcd6cae2912a9f1e6ade6416079",
            "name": "wxBot",
            "phone": [],
            "star": False,
            "type": 1
        }
    },
    "from": {
        "_events": {},
        "_eventsCount": 0,
        "id": "@68f6ad55deb901584e3dbbfa11e0f375e7594e4f9cc3b3e69c53e5ae2ecf64b3",
        "payload": {
            "address": "",
            "alias": "",
            "avatar": "",
            "city": "",
            "friend": False,
            "gender": 0,
            "id": "@68f6ad55deb901584e3dbbfa11e0f375e7594e4f9cc3b3e69c53e5ae2ecf64b3",
            "name": "",
            "phone": [],
            "province": "",
            "signature": "",
            "star": False,
            "weixin": "",
            "type": 1
        }
    }
}

**Comment by danni-cool** [comment]
wechaty应该有bug，就是新的消息可能同步联系人等有延迟，过段时间看看还这样吗

**Comment by XHHzZz** [comment]
问一个问题，文件类信息发送的时候，如果文件太大是不是会导致失败？

**Comment by XHHzZz** [comment]
但是我通过/webhook/msg  发送文件的时候，3.3M的失败了   几百k的成功了，
日志报错：Error handling POST request: AxiosError: read ECONNRESET

**Comment by XHHzZz** [comment]
另外试用fileUrl的时候，文件过大也不行
请求参数
{
    "to": "H",
    "type": "fileUrl",
    "content": "http://m7.music.126.net/20231201111906/9e9318b2ed7bbc3ee859c15cc0e942f5/ymusic/f9c6/dfa2/2b23/f01dd63311c013cdec95fdc116f8de5e.mp3",
    "isRoom": false
}
报错信息

Error handling POST request: TypeError: Cannot read properties of undefined (reading 'length')
    at new FileBox (/app/node_modules/.pnpm/file-box@1.4.15/node_modules/file-box/dist/cjs/src/file-box.js:369:45)
    at FileBox.fromBuffer (/app/node_modules/.pnpm/file-box@1.4.15/node_modules/file-box/dist/cjs/src/file-box.js:141:16)
    at Object.getMediaFromUrl (/app/src/utils/index.js:55:18)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Object.formatAndSendMsg (/app/src/service/msg.js:15:22)
    at async /app/src/route/msg.js:119:30

**Comment by danni-cool** [comment]
@XHHzZz 这个文件本身就有问题，播放不了

**Comment by XHHzZz** [comment]
@danni-cool   我尝试了本地文件，当mp3文件较大的时候，发送失败，我又使用notepad++ 打开mp3文件，删除里面的一些内容使文件变小，再次发送可以发送成功
下面是文件内容
![1](https://github.com/danni-cool/docker-wechatbot-webhook/assets/120640558/6c9a2c23-653e-4c5a-a791-0d3606b6174c)
![2](https://github.com/danni-cool/docker-wechatbot-webhook/assets/120640558/2efcdd19-19bb-4a47-be14-6f60bd2fd185)
![3](https://github.com/danni-cool/docker-wechatbot-webhook/assets/120640558/99040a4c-54a7-443c-9b54-1848dfd9a4ee)
![4](https://github.com/danni-cool/docker-wechatbot-webhook/assets/120640558/6f5eb20c-96f9-45bb-b5f1-025dfb21a264)

**Comment by ZstarsK** [comment]
我也遇到这个问题了，怎么解决，急急急。 我做的GPT机器人，每次加完好友都需要重启docker，否则获取不到新加好友的昵称，也就无法返回信息了。

**Comment by cultureship** [comment]
目前发送好友请求好像压根就收不到了

**Comment by ZstarsK** [comment]
登录状态添加好友，获取不到好友信息 v2.6.1版本修复了么？

**Comment by danni-cool** [comment]
> 登录状态添加好友，获取不到好友信息 v2.6.1版本修复了么？

暂无，目前有其他高优先级的事情

**Comment by strongFn** [comment]
新添加的好友，设置好了发送的人，执行返回的是200，但是实际上在登录号码微信界面看没有发送成功。我关掉了容器，重置容器之后再登录，还是同样的问题。是不是要等一段时间才能刷新呀？

**Comment by a76659197** [comment]
> wechaty应该有bug，就是新的消息可能同步联系人等有延迟，过段时间看看还这样吗

还是遇到这个问题，新加的好友，发送过来的好友申请没有name，发送过来的消息也没有name
