### ISSUE TITLE
微信持久在线存在问题

### ISSUE THREAD

**Issue by jiyuhei** [danni-cool/docker-wechatbot-webhook#9]
当我搭建好相关的服务，调用接口发送消息的时候，当天下午测试可以调用发送，第二天早上好像也可以调用发送，但是第三天早上可能就发送失败了，根据代码查看发现500

uncaughtException AssertionError [ERR_ASSERTION]: 3 == 0
    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)
    at /app/node_modules/wechat4u/lib/core.js:444:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 2,
  details: 'AssertionError [ERR_ASSERTION]: 3 == 0\n' +
    '    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)\n' +
    '    at /app/node_modules/wechat4u/lib/core.js:444:24\n' +
    '    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)'
}
uncaughtException GError: 状态同步超过284.609s未响应，5s后尝试重启
    at Wechat.checkPolling (/app/node_modules/wechat4u/lib/wechat.js:298:19)
    at Timeout._onTimeout (/app/node_modules/wechat4u/lib/wechat.js:319:25)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7) {
  code: 2,
  details: 'Error: 状态同步超过284.609s未响应，5s后尝试重启\n' +
    '    at Wechat.checkPolling (/app/node_modules/wechat4u/lib/wechat.js:298:19)\n' +
    '    at Timeout._onTimeout (/app/node_modules/wechat4u/lib/wechat.js:319:25)\n' +
    '    at listOnTimeout (node:internal/timers:569:17)\n' +
    '    at process.processTimers (node:internal/timers:512:7)'
}
Error handling POST request: AssertionError [ERR_ASSERTION]: 1102 == 0
    at Object.equal (/app/node_modules/wechat4u/lib/util/global.js:69:24)
    at /app/node_modules/wechat4u/lib/core.js:535:24
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PuppetWechat4u.messageSendText (/app/node_modules/wechaty-puppet-wechat4u/dist/cjs/src/puppet-wechat4u.js:635:9)
    at async WechatifiedUserClass.say (/app/node_modules/wechaty/dist/cjs/src/user-modules/room.js:371:21)
    at async formatAndSendMsg (/app/src/service/msg.js:8:7)
    at async /app/src/route/msg.js:31:28 {
  generatedMessage: true,
  code: 'ERR_ASSERTION',
  actual: 1102,
  expected: 0,

**Comment by danni-cool** [comment]
这个是wechat4u 的问题，推测是因为网页微信有风控？登录会掉线，可能只有通过掉线 - 通知 - 重新扫码登录 的流程去弥补了

**Comment by jiyuhei** [comment]
> 这是wechat4u的问题，推测是网页微信有风控？登录会掉线，可能只能通过掉线 - 通知 - 重新扫码登录的流程去弥补了因为

我经过国庆测试，发现两天掉线反复登陆几次后，这次坚持了好几天，我后来也知道是风控的问题了。

**Comment by danni-cool** [comment]
> > 这是wechat4u的问题，推测是网页微信有风控？登录会掉线，可能只能通过掉线 - 通知 - 重新扫码登录的流程去弥补了因为
> 
> 我经过国庆测试，发现两天掉线反复登陆几次后，这次坚持了好几天，我后来也知道是风控的问题了。

加入到TODO计划里，增加一个补偿机制，可以通过微信等通知到本人，通知定期及时登录 https://github.com/danni-cool/docker-wechatbot-webhook/issues/11
